language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install scipy sympy
  - wget http://bionetgen.googlecode.com/files/BioNetGen-2.2.5-stable.zip
  - unzip BioNetGen-2.2.5-stable.zip
  - sudo ln -s `pwd`/BioNetGen-2.2.5-stable /usr/local/share/BioNetGen
script: nosetests
